/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system;

/**
 *
 * @author mohamedkhaled
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtn1 = new javax.swing.JTextField();
        txte1 = new javax.swing.JTextField();
        txtm1 = new javax.swing.JTextField();
        txtp1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("signup");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 37, 71, 43));

        jLabel2.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel2.setText("name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 101, -1, -1));

        jLabel3.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel3.setText("email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 164, -1, -1));

        jLabel4.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel4.setText("mobile no");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel5.setText("password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 305, -1, -1));

        txtn1.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        getContentPane().add(txtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 98, 552, -1));

        txte1.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        txte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txte1ActionPerformed(evt);
            }
        });
        getContentPane().add(txte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 164, 552, -1));

        txtm1.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        txtm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtm1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 227, 552, -1));

        txtp1.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        getContentPane().add(txtp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 302, 556, -1));

        jButton1.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jButton1.setText("save");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 427, -1, -1));

        jButton2.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 427, -1, -1));

        jButton3.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jButton3.setText("exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 427, -1, -1));

        jButton4.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jButton4.setText("forgot password?");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 527, -1, -1));

        jButton5.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jButton5.setText("login");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 527, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abstract-blur-supermarket.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(1500, 1000));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, -12, 5560, 3670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txte1ActionPerformed

    private void txtm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtm1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txte1;
    private javax.swing.JTextField txtm1;
    private javax.swing.JTextField txtn1;
    private javax.swing.JPasswordField txtp1;
    // End of variables declaration//GEN-END:variables
}
